---
glob: "app/**/*.{html,text,js}{+*,}.erb"
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
  - 'lib/**/*'
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Rails/Presence:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Style/RedundantCondition:
        Enabled: false
      Layout/HashAlignment:
        Enabled: false
      Rails/LinkToBlank:
        Enabled: false
      Layout/SpaceInsideHashLiteralBraces:
        Enabled: false
      Style/StringLiteralsInInterpolation:
        Enabled: false
      Layout/ArgumentAlignment:
        Enabled: false
      Style/SafeNavigation:
        Enabled: false
      Style/TrailingCommaInHashLiteral:
        Enabled: false
      Style/RedundantParentheses:
        Enabled: false
      Lint/FloatComparison:
        Enabled: false
      Style/TrailingCommaInArguments:
        Enabled: false
      Layout/EndAlignment:
        Enabled: false
      Rails/DurationArithmetic:
        Enabled: false
      Style/HashConversion:
        Enabled: false
      Layout/ElseAlignment:
        Enabled: false
      Layout/IndentationWidth:
        Enabled: false
      Style/TrailingCommaInArrayLiteral:
        Enabled: false
      Style/IfWithBooleanLiteralBranches:
        Enabled: false
  SelfClosingTag:
    enabled: false
  NoJavascriptTagHelper:
    enabled: false
