# DEFAULT CONNECTION CONFIGURATION
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>

development:
  primary:
    <<: *default
    database: gatherpack_development
    host: localhost
  versions:
    <<: *default
    database: gatherpack_development_versions
    host: localhost
    migrations_paths: db/versions_migrate

test:
  primary:
    <<: *default
    database: gatherpack_test
    host: localhost
  versions:
    <<: *default
    database: gatherpack_development_versions
    host: localhost
    migrations_paths: db/versions_migrate

production:
  primary:
    <<: *default
    host: localhost
    database: gatherpack_production
  versions:
    <<: *default
    database: gatherpack_development_versions
    host: localhost
    migrations_paths: db/versions_migrate
